@startuml
start
if (Пользователь имеет ЛК?) then (да)
    :Авторизация;
    :Проверка данных;
else (нет)
    :Регистрация;
    :Проверка данных;
    :Создание ЛК;
endif
:Доступ в ЛК;
:Витрина товаров;
:Добавление товара в корзину;
if (товар в наличии) then (да)
    :Выбор способа оплаты;
    :Выбор способа заказа;
    :Оплата товара;
else (товара нет в наличии)
    

end
@enduml


