@startuml

actor           "Покупатель"        as  user
participant     "WebUI"             as  web
participant     "Order Controller"  as  manager
participant     "Payment Service"   as  billing
database        "Database"          as  db #lightYellow
participant     "Notification center" as notification

group Оформление заказа
    user    ->  web     :запрос на оформление заказа
    activate web
    web     ->  manager :передача данных заказа
    activate manager
    manager ->  db      :сохранение заказа
    activate db
    db      --[#LightBlue]> manager :confirmation
    note right :Сохранение заказа в статусе ожидает
    deactivate db
end

group Оплата
    manager ->  billing :проведение платежа
    activate billing
    alt
        billing -[#green]>  manager :подтверждение транзакции
        else
        billing -[#red]>  manager :ошибка оплаты
        deactivate billing
    end
    end

group Подтверждение
    manager -[#green]>  web     :подтверждение заказа
    deactivate manager
    web     -[#green]>  user    :детали заказа
    deactivate web
    notification -> user :Уведомление
end

group Изменение корзины
    user -> web :изменение заказа
    note right :добавление или удаление экземпляров
    activate web
    web -> manager :передача изменений
    activate manager
    manager ->  db      :сохранение заказа
    activate db
    db      --[#LightBlue]> manager :confirmation
    deactivate db
end

group Оплата
    manager ->  billing :проведение платежа
    activate billing
    alt
        billing -[#green]>  manager :подтверждение транзакции
        else
        billing -[#red]>  manager :ошибка оплаты
        deactivate billing
    end
    end

group Подтверждение
    manager -[#green]>  web     :подтверждение заказа
    deactivate manager
    web     -[#green]>  user    :детали заказа
    deactivate web
    notification -> user :Уведомление
end    

@enduml