@startumlname Упражение and_xor
start
if (Пользователь имеет ЛК?) then (Да)
    :Авторизация;
    :Проверка данных;
else (Нет)
    :Регистрация;
    :Проверка данных;
    :Создание ЛК;
endif
:Доступ в ЛК;
:Витрина товаров;
:Добавление товара\nв корзину;
if (Товар в наличии) then (Товар\nв наличии)
    :Переход к выбору\nспособа оплаты\nи способа доставки;
else (Товара нет\nв наличии)
    fork
        :Уведомление\nоб отсутствии товара;
    fork again
        :Предложение\nаналогичных товаров;
    fork again
        :Подписаться\nна уведомление\nо наличии;
    end fork
    stop
endif
fork
    :Выбор способа оплаты;
    :Выбор способа заказа;
    :Оплата товара;
fork again
    :Уведомление\nо заказе на склад;
    :Комплектация заказа;
end fork
repeat :Проверка оплаты;
    if (Оплата) then (Да)
        
    else (Нет)
        :Уведомление\nо проблеме\nс платежом;
        fork
            :Повторить\nпопытку\nоплаты;
        fork again
            :Изменить\nспособ\nоплаты;
        end fork
    endif
    if (Решение клиента) then (Решение\nположительное)
        
    else (Решение\nотрицательное)
        :Отмена заказа;
        stop
    endif
backward :Смена\nспособа\nоплаты;
repeat while (Оплата прошла)
:Создание\nсчета-фактуры;
:Уведомление\nо создании\nзаказа;
:Перевод заказа\nв статус "Отправлен";
end
@enduml


