@startuml
class PaymentManager {
  - managerID
  - managerName
  + processAllPayments()
}

abstract Payment {
  - amount
  - paymentDate
  - transactionID
  processPayment()
}

class CashPayment {
  - cashProvided
  - change
}

class CardPayment {
  - cardNumber
  - cardHolder
  - cardExpirationDate
  - validationType
}

PaymentManager <|-- Payment
Payment <|-- CashPayment
Payment <|-- CardPayment

@enduml