@startuml

left to right direction

actor "Клиент" as Client 
actor "Сотрудник банка" as Employee
actor "Служба безопасности" as SB 
actor "Бюро кредитных историй (БКИ)" as BKI 



Client -> (Подать заявку)
(Подать заявку) -> (Рассмотреть заявку) : include

Employee -> (Рассмотреть заявку)
(Рассмотреть заявку) .> (Запросить кредитную историю) : extend
(Запросить кредитную историю) -> BKI
(Рассмотреть заявку) -> (Проверить безопасность) : include <<Обязательно>>
(Проверить безопасность) -> SB

(Одобрить заявку) .> (Рассмотреть заявку) : extend
(Отклонить заявку) .> (Рассмотреть заявку) : extend <<Если проверка СБ не пройдена>>

@enduml